openapi: 3.0.0
info:
  title: Example API.
  description: Example interface contract.
  version: 1.0.0
paths:
  /files:
    get:
      summary: Returns a list of files.
      responses:
        '200':
          description: A JSON array of file names.
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string